# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDeploy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDeploy(object):
    def setupUi(self, AddDeploy):
        AddDeploy.setObjectName("AddDeploy")
        AddDeploy.resize(1640, 760)
        AddDeploy.setMinimumSize(QtCore.QSize(1640, 760))
        AddDeploy.setMaximumSize(QtCore.QSize(1640, 760))
        self.centralwidget = QtWidgets.QWidget(AddDeploy)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_DestPath = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_DestPath.setGeometry(QtCore.QRect(740, 50, 681, 31))
        self.textEdit_DestPath.setObjectName("textEdit_DestPath")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 10, 111, 21))
        self.label_2.setObjectName("label_2")
        self.Btn_SelectSourceFiles = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_SelectSourceFiles.setGeometry(QtCore.QRect(140, 10, 101, 21))
        self.Btn_SelectSourceFiles.setMinimumSize(QtCore.QSize(0, 0))
        self.Btn_SelectSourceFiles.setObjectName("Btn_SelectSourceFiles")
        self.Btn_SelectDestinationPath = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_SelectDestinationPath.setGeometry(QtCore.QRect(850, 10, 101, 21))
        self.Btn_SelectDestinationPath.setMinimumSize(QtCore.QSize(0, 0))
        self.Btn_SelectDestinationPath.setObjectName("Btn_SelectDestinationPath")
        self.textEdit_SourceFiles = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_SourceFiles.setGeometry(QtCore.QRect(20, 50, 591, 481))
        self.textEdit_SourceFiles.setObjectName("textEdit_SourceFiles")
        AddDeploy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddDeploy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1640, 21))
        self.menubar.setObjectName("menubar")
        AddDeploy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddDeploy)
        self.statusbar.setObjectName("statusbar")
        AddDeploy.setStatusBar(self.statusbar)

        self.retranslateUi(AddDeploy)
        QtCore.QMetaObject.connectSlotsByName(AddDeploy)

    def retranslateUi(self, AddDeploy):
        _translate = QtCore.QCoreApplication.translate
        AddDeploy.setWindowTitle(_translate("AddDeploy", "MainWindow"))
        self.label.setText(_translate("AddDeploy", "Source Files:"))
        self.label_2.setText(_translate("AddDeploy", "Destination Path:"))
        self.Btn_SelectSourceFiles.setText(_translate("AddDeploy", "Select Files"))
        self.Btn_SelectDestinationPath.setText(_translate("AddDeploy", "Select Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDeploy = QtWidgets.QMainWindow()
    ui = Ui_AddDeploy()
    ui.setupUi(AddDeploy)
    AddDeploy.show()
    sys.exit(app.exec_())
